### ISSUE TITLE
Storefront

### ISSUE THREAD

**Issue by elliottsj** [cssu/trackary#1]
The storefront should have these features:
- Browse items sold by the CSSU
- Each item has:
  - Name
  - Image
  - Description
  - Price in CAD
  - Price in reward points
  - Amount in stock

**Comment by arkon** [comment]
Is the storefront for admin use only?

**Comment by jwebbed** [comment]
I want to lock the purchase page to mac addresses, particularly the tablet in the office. +DB access with login

**Comment by elliottsj** [comment]
@arkon Nope. This is the public-facing side
