### ISSUE TITLE
Remove {{src}} hack

### ISSUE THREAD

**Issue by elliottsj** [cssu/trackary#13]
[A hack-y fix was added](https://github.com/cssu/trackary/commit/586c000d9c3fb55d374793bc87d15b8b17fe3380) to fix https://github.com/ahuth/emcee/issues/28 and https://github.com/ahuth/emcee/issues/29. This should be removed once issues with [emcee](https://github.com/ahuth/emcee) are resolved.

**Comment by ahuth** [comment]
The issues should be fixed in v1.0.8 of Emcee, now. Thanks for your patience with this.

**Comment by elliottsj** [comment]
Thanks!
