### ISSUE TITLE
Use existing ASP.NET project?

### ISSUE THREAD

**Issue by arkon** [cssu/trackary#14]
FWIW, I made an ASP.NET version of this at one point: https://github.com/arkon/trackary

**Comment by elliottsj** [comment]
:+1: 
I'm not planning on doing any more work on this; maybe @qasim / @ivanzhangio / @xMrWhite will want to work on it for current CSSU though

**Comment by arkon** [comment]
The project's been since transferred over to the CSSU account: https://github.com/cssu/trackary-asp
