### ISSUE TITLE
Reward points

### ISSUE THREAD

**Issue by elliottsj** [cssu/trackary#2]
We need to work out some details for a customer loyalty/reward program:
- What is the name of our 'reward points'?
- How many points are awarded when making a purchase?
  - Fixed amount per dollar/cent?
  - Extra points when buying multiple items?
- How many points are required to redeem an item?

**Comment by arkon** [comment]
Also, how do we manage them? Do you scroll through a list of people? Or maybe we can scan their TCards?

**Comment by elliottsj** [comment]
I'm thinking we use their UTORids. That way we can also email them (e.g. ellio128@mail.utoronto.ca)

**Comment by arkon** [comment]
Why not also set it up to store their TCard barcode number? It'd be easier/quicker to scan their card when making a purchase (using the Surface RT's camera).

**Comment by elliottsj** [comment]
I wonder if their TCard barcode has their UTORid/email info attached somehow. This is what I'm thinking:

Customer buys an item, hands their TCard to the cashier -> Cashier records their UTORid and does the transaction -> (If the customer doesn't yet have an account, they receive an email with their account info)

**Comment by arkon** [comment]
I was basically thinking of a User model like so
- Name
- Photo
- TCard barcode number
- Points
- UTORid (maybe)
- email (maybe)

Then on the first transaction: set up account with the aforementioned info.
On any subsequent transaction, points can be added/deducted from the specific User, which can be quickly found by scanning the TCard (although you can also just search for the User's name).

**Comment by arkon** [comment]
This may be useful for barcode scanning: http://devblog.blackberry.com/2014/05/using-html5-to-scan-1d-and-2d-barcodes/

It might even be useful for scanning merchandise.

**Comment by arkon** [comment]
Okay, so as far as I can tell, the TCard barcodes are in Codabar format. Not sure if there's any library out there that reads these.

**Comment by jwebbed** [comment]
Something else to consider is allowing people to check reward points on their own. Maybe allow them to sign up using their student number or something identifiable they only really should have access to.

**Comment by elliottsj** [comment]
@jwebbed Had that in the readme, but didn't create an issue for it until now: https://github.com/cssu/trackary/issues/7
